### ISSUE TITLE
'timelength' for each, individual view?

### ISSUE THREAD

**Issue by Subtract** [hawkfalcon/ServerTutorial#22]
Hey.

This might not be the right place to post this, but:

Would it be possible to implement a `timelength` parameter for each different view instead of the whole tutorial? I want to be able to have one view last 5 seconds, then have another one last 10 seconds due to the amount of text it might have, or to just let people look around the scene itself. I'd like to be able to let people read the text without being bombarded with another flicker of it when the next view arrives.

Example:

```
 views:
      '1':
        message: '1'
        messagetype: TITLE
        location: <location>
        timelength: '5'
      '2':
        message: '2'
        messagetype: TITLE
        location: <location>
        timelength: '10'
      '3':
        message: '3'
        messagetype: TITLE
        location: <location>
        timelength: '3'
     'etc'...
```

Thanks!
